import { createContext, useContext, useState, useCallback } from "react";

const translations = {
  EN: {
    navAbout: "About",
    navProjects: "Projects",
    navExp: "Exp.",
    navContact: "Contact",
    heroTitle: "Hi, I'm ",
    heroName: "Oscar",
    heroSubtitle: "I'm a ",
    heroRole: "Frontend Developer",
    heroDescription: "Passionate about building web experiences and continuously learning new technologies. With over 13 years in IT support, I'm now transitioning into frontend development.",
    contactBtn: "Contact Me",
    aboutTitle: "About",
    aboutP1: "y! I'm Oscar. With a background in IT support and a passion for technology, I've spent 13 years helping users solve complex problems at multinational companies.",
    aboutP2: "Currently, I'm expanding my skills toward frontend development, building modern web applications with React and Next.js.",
    aboutP3: "I love combining my problem-solving abilities with new coding skills to create intuitive user experiences.",
    aboutP4: "I'm always open to new opportunities where I can merge my IT experience with my passion for development.",
    aboutMyLinks: "My links",
    statsUseAtWork: "Use at work",
    statsUseForFun: "Use for fun",
    statsWindows: "Windows",
    statsNetwork: "Network",
    statsTroubleshooting: "Troubleshooting",
    statsDocumentation: "Documentation",
    statsServiceNow: "ServiceNow",
    statsIntune: "Intune",
    statsMicrosoft: "Microsoft",
    statsApple: "Apple",
    statsHardware: "Hardware",
    statsJS: "JavaScript",
    statsReact: "React",
    statsTailwind: "Tailwind",
    statsHTML: "HTML",
    statsCSS: "CSS",
    statsGit: "Git",
    statsGitHub: "GitHub",
    projectsTitle: "Projects",
    projectLinks: "Project Links",
    projectLearnMore: "Learn more",
    projectSourceCode: "Source Code",
    projectLiveProject: "Live Project",
    experienceTitle: "Experience",
    contactTitle: "Contact",
    contactText: "Shoot me an email if you want to connect! You can also find me on",
    contactLinkedin: "Linkedin",
    contactTwitter: "Twitter",
    contactOr: "or",
    contactEmail: "oscar@email.com",
    resumeBtn: "My Resume",
    typewriter1: "IT Support Sr. Analyst",
    typewriter2: "Frontend Developer",
    plenitudTitle: "Plenitud Fit",
    plenitudDescription: "Landing page for a functional training gym in Montevideo, Uruguay. Modern and responsive design.",
    plenitudModal1: "PlenitudFit is a functional training gym located in Montevideo, Uruguay. Operating since 2016, they specialize in sports training and healthy lifestyle promotion.",
    plenitudModal2: "I developed a modern and responsive landing page that presents their services, activities, schedules, and membership plans in a clear and attractive way.",
    plenitudModal3: "The website helps new members learn about the gym, view class schedules, and get contact information quickly and easily.",
    cfrTitle: "CFR Estudio",
    cfrDescription: "Website for an architecture studio in Montevideo, Uruguay. Presents architectural projects and services.",
    cfrModal1: "CFR Estudio is an architecture studio located in Montevideo, Uruguay, specialized in residential and commercial projects.",
    cfrModal2: "I developed a professional website that showcases their project portfolio, services offered, and contact information.",
    cfrModal3: "The design reflects the studio's architectural aesthetic, focusing on the visual presentation of their works and projects.",
    revisionTitle: "Revision Automotriz",
    revisionDescription: "Website for a used vehicle inspection service in Uruguay. Presents automotive inspection services.",
    revisionModal1: "Revision Automotriz is a vehicle inspection service that helps used car buyers make informed decisions.",
    revisionModal2: "I developed the website with React and Bootstrap, presenting their inspection services for over 200 vehicle points.",
    revisionModal3: "The site includes information about the inspection process, service benefits, and contact methods to request an inspection.",
  },
  ES: {
    navAbout: "Sobre mí",
    navProjects: "Proyectos",
    navExp: "Exp.",
    navContact: "Contacto",
    heroTitle: "Hola, soy ",
    heroName: "Oscar",
    heroSubtitle: "Soy ",
    heroRole: "Desarrollador Frontend",
    heroDescription: "Apasionado por construir experiencias web y aprendiendo constantemente nuevas tecnologías. Con más de 13 años en soporte de TI, ahora me estoy transfiriendo al desarrollo frontend.",
    contactBtn: "Contáctame",
    aboutTitle: "Sobre mí",
    aboutP1: "ola! Soy Oscar. Con experiencia en soporte de TI y pasión por la tecnología, he pasado 13 años ayudando a usuarios a resolver problemas complejos en empresas multinacionales.",
    aboutP2: "Actualmente, estoy expandiendo mis habilidades hacia el desarrollo frontend, construyendo aplicaciones web modernas con React y Next.js.",
    aboutP3: "Me encanta combinar mis habilidades de resolución de problemas con nuevas habilidades de codificación para crear experiencias de usuario intuitivas.",
    aboutP4: "Siempre estoy abierto a nuevas oportunidades donde pueda combinar mi experiencia en TI con mi pasión por el desarrollo.",
    aboutMyLinks: "Mis enlaces",
    statsUseAtWork: "Uso en el trabajo",
    statsUseForFun: "Uso por hobby",
    statsWindows: "Windows",
    statsNetwork: "Network",
    statsTroubleshooting: "Troubleshooting",
    statsDocumentation: "Documentation",
    statsServiceNow: "ServiceNow",
    statsIntune: "Intune",
    statsMicrosoft: "Microsoft",
    statsApple: "Apple",
    statsHardware: "Hardware",
    statsJS: "JavaScript",
    statsReact: "React",
    statsTailwind: "Tailwind",
    statsHTML: "HTML",
    statsCSS: "CSS",
    statsGit: "Git",
    statsGitHub: "GitHub",
    projectsTitle: "Proyectos",
    projectLinks: "Enlaces del Proyecto",
    projectLearnMore: "Ver más",
    projectSourceCode: "Código Fuente",
    projectLiveProject: "Proyecto en Vivo",
    experienceTitle: "Experiencia",
    contactTitle: "Contacto",
    contactText: "¡Escríbeme un email si quieres conectar! También puedes encontrarme en",
    contactLinkedin: "Linkedin",
    contactTwitter: "Twitter",
    contactOr: "o",
    contactEmail: "oscar@email.com",
    resumeBtn: "Mi CV",
    typewriter1: "Analista Sr. de Soporte IT",
    typewriter2: "Desarrollador Frontend",
    plenitudTitle: "Plenitud Fit",
    plenitudDescription: "Landing page para gimnasio de entrenamiento funcional en Montevideo, Uruguay. Diseño moderno y responsive.",
    plenitudModal1: "PlenitudFit es un gimnasio de entrenamiento funcional ubicado en Montevideo, Uruguay. Operando desde 2016, se especializan en entrenamiento deportivo y promoción de vida saludable.",
    plenitudModal2: "Desarrollo una landing page moderna y responsive que presenta sus servicios, actividades, horarios y planes de membresía de forma clara y atractiva.",
    plenitudModal3: "El sitio web ayuda a nuevos miembros a conocer el gimnasio, ver horarios de clases y obtener información de contacto de manera rápida y sencilla.",
    cfrTitle: "CFR Estudio",
    revisionTitle: "Revision Automotriz",
    revisionDescription: "Sitio web para servicio de revision de vehiculos usados en Uruguay. Presenta servicios de inspeccion automotriz.",
    revisionModal1: "Revision Automotriz es un servicio de inspeccion vehicular que ayuda a compradores de vehiculos usados a tomar decisiones informadas.",
    revisionModal2: "Desarrollo el sitio web con React y Bootstrap, presentando sus servicios de revision de mas de 200 puntos del vehiculo.",
    revisionModal3: "El sitio incluye informacion sobre el proceso de inspeccion, beneficios del servicio y formas de contacto para solicitar una revision.",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("EN");
  const [transitionKey, setTransitionKey] = useState(0);

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === "EN" ? "ES" : "EN"));
    setTransitionKey((prev) => prev + 1);
  }, []);

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, transitionKey }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
