import { createContext, useContext, useState, useCallback } from "react";

const translations = {
  EN: {
    navAbout: "About",
    navProjects: "Projects",
    navExp: "Exp.",
    navContact: "Contact",
    heroTitle: "Hi, I'm ",
    heroName: "Oscar",
    heroSubtitle: "I'm a ",
    heroRole: "Frontend Developer",
    heroDescription: "Passionate about building web experiences and continuously learning new technologies. With a lot of experience in IT support, I'm now immersing, training and testing this world of frontend development.",
    contactBtn: "Contact Me",
    aboutTitle: "About",
    aboutP1: "Hi! I'm Oscar. I've spent over 13 years working in IT support, helping users solve real problems in demanding, multinational environments. That experience shaped the way I approach technology: not just from a technical perspective, but from understanding how tools impact people's day-to-day work.",
    aboutP2: "Currently, I'm transitioning into frontend development, building modern web applications with React and Next.js. I'm especially interested in creating clean, intuitive interfaces that actually make a difference for users.",
    aboutP3: "I enjoy combining my background in problem-solving with development, bringing a more practical and user-focused approach to the products I build.",
    aboutP4: "I'm always open to new opportunities where I can grow as a developer and merge my IT experience with my passion for building.",
    aboutMyLinks: "My links",
    statsUseAtWork: "Use at work",
    statsUseForFun: "Use for fun",
    statsWindows: "Windows",
    statsNetwork: "Network",
    statsTroubleshooting: "Troubleshooting",
    statsDocumentation: "Documentation",
    statsServiceNow: "ServiceNow",
    statsIntune: "Intune",
    statsMicrosoft: "Microsoft",
    statsApple: "Apple",
    statsHardware: "Hardware",
    statsJS: "JavaScript",
    statsReact: "React",
    statsTailwind: "Tailwind",
    statsHTML: "HTML",
    statsCSS: "CSS",
    statsGit: "Git",
    statsGitHub: "GitHub",
    projectsTitle: "Projects",
    projectLinks: "Project Links",
    projectLearnMore: "Learn more",
    projectSourceCode: "Source Code",
    projectLiveProject: "Live Project",
    experienceTitle: "Experience",
    contactTitle: "Contact",
    contactText: "Shoot me an email if you want to connect! You can also find me on",
    contactLinkedin: "Linkedin",
    contactTwitter: "GitHub",
    contactOr: "or",
    contactEmail: "oscar@email.com",
    resumeBtn: "My Resume",
    typewriter1: "IT Support Sr. Analyst",
    typewriter2: "Frontend Developer",
    expRciTitle: "RCI Latinoamericana (Travel + Leisure)",
    expRciPos: "Sr. Help Desk Support Analyst",
    expRciTime: "Apr 2017 - Present",
    expRciDesc: "Currently working at RCI Latin America within the IT support team, in a large corporate environment with modern management tools.",
    expRciDesc2: "My role combines incident resolution with team administration and continuous process improvement. I work primarily with Intune and Autopilot for device provisioning and configuration, as well as ServiceNow for ticket management and documentation.",
    expRciDesc3: "I also participate in operating system deployments and task optimization, incorporating automation with PowerShell when possible.",
    expRciDesc4: "As I grew in the role, I started to have a broader vision of support, understanding not only the technical aspects but also how each solution affects the daily operation of the teams. As each team functions like a gear in a machine and how the time of our solutions affects the final numbers of the year, or as they say \"Les Miserables - At the end of the day\".",
    expRciDesc5: "Beyond the technical side, RCI is a place where I really feel comfortable working. The team culture, the environment, and the way of working make day-to-day very positive, and it is one of the main reasons why I continue to develop professionally here.",
    expItsTitle: "ITS - Infrastructure Technology Services",
    expItsPos: "Help Desk Analyst",
    expItsTime: "May 2016 - Apr 2017",
    expItsDesc: "At ITS, I worked providing IT support for Telefonica Business Solutions in a corporate environment with high service standards.",
    expItsDesc2: "Although it was a short experience, it was a key stage in my development because it allowed me to integrate into a larger ecosystem, working within Zonamerica for the first time.",
    expItsDesc3: "During that time, I worked resolving incidents, managing tickets, and providing support to users in a context where speed and clarity in communication were essential.",
    expItsDesc4: "Additionally, it was during this stage that I met RCI, a company I later joined and where I continue to grow professionally.",
    expInfoTitle: "Infocorp",
    expInfoPos: "Help Desk Analyst",
    expInfoTime: "Dec 2012 - May 2016",
    expInfoDesc: "At Infocorp, I provided IT support for various companies, but the one that taught me the most was CPA Ferrere, a large corporate environment with over 500 users and high demands.",
    expInfoDesc2: "My role involved resolving day-to-day incidents, but also adapting to a very dynamic work pace where response times and quality of support were key.",
    expInfoDesc3: "It was an experience where I gained solidity: I learned to prioritize, handle pressure, and solve problems more efficiently.",
    techITIL: "ITIL",
    techEnglish: "English Support",
    techAdaptation: "Fast Adaptation",
    techWindows: "Windows",
    techWindowsAIK: "Windows AIK",
    techSysprep: "Sysprep",
    techOffice365: "Office 365",
    techVendor: "Vendor Management",
    techNetworking: "Networking",
    techIOS: "iOS",
    techDataCenter: "Data Center",
    techCoordination: "Coordination",
    techVIP: "VIP Support",
    techGlobal: "Global Support",
    techHardware: "Hardware Repair",
    techDataMigration: "Data Migration",
    techBackups: "Backups",
    techDGI: "DGI Software",
    techAutopilot: "Autopilot",
    techCrowdstrike: "Crowdstrike",
    techSCCM: "SCCM",
    techMSTeams: "MS Teams",
    techMicrosoftServer: "Microsoft Server",
    techSnowflake: "Snowflake",
    techSQL: "SQL",
    techPowerBi: "PowerBi",
    techZscaler: "Zscaler",
    techVPN: "VPN",
    techMeraki: "Meraki",
    techPaperCut: "PaperCut",
    techOSDImages: "OSD Images",
    techBitlocker: "Bitlocker",
    techGlobalTeams: "Global Teams",
    techGlobalSupport: "Global Support",
    techMassiveMigrations: "Massive Migrations",
    plenitudTitle: "Plenitud Fit",
    plenitudDescription: "Landing page for a functional training gym in Montevideo, Uruguay. Modern and responsive design.",
    plenitudModal1: "PlenitudFit is a functional training gym located in Montevideo, Uruguay.",
    plenitudModal2: "I developed a modern and responsive landing page that presents their services.",
    plenitudModal3: "The website helps new members learn about the gym and get contact information.",
    cfrTitle: "CFR Estudio",
    cfrDescription: "Website for an architecture studio in Montevideo, Uruguay.",
    cfrModal1: "CFR Estudio is an architecture studio specialized in residential and commercial projects.",
    cfrModal2: "I developed a professional website that showcases their project portfolio.",
    cfrModal3: "The design reflects the studio's architectural aesthetic.",
    revisionTitle: "Revision Automotriz",
    revisionDescription: "Website for a used vehicle inspection service in Uruguay.",
    revisionModal1: "Revision Automotriz is a vehicle inspection service that helps used car buyers make informed decisions.",
    revisionModal2: "I developed the website with React and Bootstrap.",
    revisionModal3: "The site includes information about the inspection process and service benefits.",
  },
  ES: {
    navAbout: "Sobre mi",
    navProjects: "Proyectos",
    navExp: "Exp.",
    navContact: "Contacto",
    heroTitle: "Hola, soy ",
    heroName: "Oscar",
    heroSubtitle: "Soy ",
    heroRole: "Desarrollador Frontend",
    heroDescription: "Apasionado por construir experiencias web y aprendiendo constantemente nuevas tecnologías. Con mucha experiencia en soporte de TI, ahora estoy incursionando, capacitándome y probando este mundo del desarrollo frontend.",
    contactBtn: "Contáctame",
    aboutTitle: "Sobre mí",
    aboutP1: "¡Hola! Soy Oscar. He pasado más de 13 años trabajando en soporte de TI, ayudando a usuarios a resolver problemas reales en entornos exigentes y multinacionales. Esa experiencia dio forma a mi forma de abordar la tecnología: no solo desde una perspectiva técnica, sino entendiendo cómo las herramientas impactan el trabajo diario de las personas.",
    aboutP2: "Actualmente, me estoy transicionando al desarrollo frontend, construyendo aplicaciones web modernas con React y Next.js. Estoy especialmente interesado en crear interfaces limpias e intuitivas que realmente marquen la diferencia para los usuarios.",
    aboutP3: "Disfruto combinar mi experiencia en resolución de problemas con el desarrollo, aportando un enfoque más práctico y centrado en el usuario a los productos que construyo.",
    aboutP4: "Siempre estoy abierto a nuevas oportunidades donde pueda crecer como desarrollador y fusionar mi experiencia en TI con mi pasión por construir.",
    aboutMyLinks: "Mis enlaces",
    statsUseAtWork: "Uso en el trabajo",
    statsUseForFun: "Uso por hobby",
    statsWindows: "Windows",
    statsNetwork: "Network",
    statsTroubleshooting: "Troubleshooting",
    statsDocumentation: "Documentation",
    statsServiceNow: "ServiceNow",
    statsIntune: "Intune",
    statsMicrosoft: "Microsoft",
    statsApple: "Apple",
    statsHardware: "Hardware",
    statsJS: "JavaScript",
    statsReact: "React",
    statsTailwind: "Tailwind",
    statsHTML: "HTML",
    statsCSS: "CSS",
    statsGit: "Git",
    statsGitHub: "GitHub",
    projectsTitle: "Proyectos",
    projectLinks: "Enlaces del Proyecto",
    projectLearnMore: "Ver mas",
    projectSourceCode: "Codigo Fuente",
    projectLiveProject: "Ver Proyecto",
    experienceTitle: "Experiencia",
    contactTitle: "Contacto",
    contactText: "Envíame un email si quieres conectar! También puedes encontrarme en",
    contactLinkedin: "Linkedin",
    contactTwitter: "GitHub",
    contactOr: "o",
    contactEmail: "oalcalde211@gmail.com",
    resumeBtn: "Mi CV",
    typewriter1: "Analista Sr. Soporte TI",
    typewriter2: "Desarrollador Frontend",
    expRciTitle: "RCI Latinoamericana (Travel + Leisure)",
    expRciPos: "Analista Sr. Soporte Help Desk",
    expRciTime: "Abr 2017 - Presente",
    expRciDesc: "Actualmente trabajo en RCI Latinoamérica dentro del equipo de soporte IT, en un entorno corporativo grande y con herramientas modernas de gestión.",
    expRciDesc2: "Mi rol combina la resolución de incidencias con la administración de equipos y la mejora continua de procesos. Trabajo principalmente con Intune y Autopilot para la provisión y configuración de dispositivos, además de ServiceNow para la gestión de tickets y documentación.",
    expRciDesc3: "También participo en despliegues de sistemas operativos y en la optimización de tareas, incorporando automatización con PowerShell cuando es posible.",
    expRciDesc4: "A medida que fui creciendo en el rol, empecé a tener una visión más amplia del soporte, entendiendo no solo lo técnico sino también como cada solución afecta la operación diaria de los equipos. Como cada equipo funciona como un engranaje dentro de una máquina y como el tiempo de nuestras soluciones afectan el número final del año, o como dicen \"Les Miserables - At the end of the day\".",
    expRciDesc5: "Más allá de lo técnico, RCI es un lugar donde realmente me siento cómodo trabajando. La cultura del equipo, el ambiente y la forma de trabajar hacen que el día a día sea muy positivo, y es uno de los principales motivos por los que sigo desarrollándome profesionalmente acá.",
    expItsTitle: "ITS - Infrastructure Technology Services",
    expItsPos: "Analista Help Desk",
    expItsTime: "May 2016 - Abr 2017",
    expItsDesc: "En ITS, trabajé proporcionando soporte de TI para Telefónica Business Solutions en un entorno corporativo con altos estándares de servicio.",
    expItsDesc2: "Aunque fue una experiencia corta, fue una etapa clave en mi desarrollo porque me permitió integrarme en un ecosistema más grande, trabajando dentro de Zonamérica por primera vez.",
    expItsDesc3: "Durante ese tiempo, trabajé resolviendo incidentes, gestionando tickets y proporcionando soporte a usuarios en un contexto donde la velocidad y la claridad en la comunicación eran esenciales.",
    expItsDesc4: "Adicionalmente, fue durante esta etapa que conocí a RCI, una empresa a la que luego me uní y donde sigo creciendo profesionalmente.",
    expInfoTitle: "Infocorp",
    expInfoPos: "Analista Help Desk",
    expInfoTime: "Dic 2012 - May 2016",
    expInfoDesc: "En Infocorp, proporcioné soporte de TI para varias empresas, pero la que más me enseñó fue CPA Ferrere, un entorno corporativo grande con más de 500 usuarios y altas demandas.",
    expInfoDesc2: "Mi rol implicaba resolver incidentes diarios, pero también adaptarme a un ritmo de trabajo muy dinámico donde los tiempos de respuesta y la calidad del soporte eran clave.",
    expInfoDesc3: "Fue una experiencia donde gané solidez: aprendí a priorizar, manejar la presión y resolver problemas de manera más eficiente.",
    techITIL: "ITIL",
    techEnglish: "Soporte en Ingles",
    techAdaptation: "Adaptación Rápida",
    techWindows: "Windows",
    techWindowsAIK: "Windows AIK",
    techSysprep: "Sysprep",
    techOffice365: "Office 365",
    techVendor: "Gestión de Vendors",
    techNetworking: "Networking",
    techIOS: "iOS",
    techDataCenter: "Centro de Datos",
    techCoordination: "Coordinación",
    techVIP: "Soporte VIP",
    techGlobal: "Soporte Global",
    techHardware: "Reparacion de Hardware",
    techDataMigration: "Migracion de Datos",
    techBackups: "Backups",
    techDGI: "Software DGI",
    techAutopilot: "Autopilot",
    techCrowdstrike: "Crowdstrike",
    techSCCM: "SCCM",
    techMSTeams: "MS Teams",
    techMicrosoftServer: "Microsoft Server",
    techSnowflake: "Snowflake",
    techSQL: "SQL",
    techPowerBi: "PowerBi",
    techZscaler: "Zscaler",
    techVPN: "VPN",
    techMeraki: "Meraki",
    techPaperCut: "PaperCut",
    techOSDImages: "Imágenes OSD",
    techBitlocker: "Bitlocker",
    techGlobalTeams: "Equipos Globales",
    techGlobalSupport: "Soporte Global",
    techMassiveMigrations: "Migraciones Masivas",
    plenitudTitle: "Plenitud Fit",
    plenitudDescription: "Página web para un gimnasio de entrenamiento funcional en Montevideo, Uruguay. Diseño moderno y responsivo.",
    plenitudModal1: "PlenitudFit es un gimnasio de entrenamiento funcional ubicado en Montevideo, Uruguay.",
    plenitudModal2: "Desarrollé una página web moderna y responsiva que presenta sus servicios.",
    plenitudModal3: "El sitio web ayuda a nuevos miembros a conocer el gimnasio y obtener información de contacto.",
    cfrTitle: "CFR Estudio",
    cfrDescription: "Sitio web para un estudio de arquitectura en Montevideo, Uruguay.",
    cfrModal1: "CFR Estudio es un estudio de arquitectura especializado en proyectos residenciales y comerciales.",
    cfrModal2: "Desarrollé un sitio web profesional que muestra su portafolio de proyectos.",
    cfrModal3: "El diseño refleja la estética arquitectónica del estudio.",
    revisionTitle: "Revisión Automotriz",
    revisionDescription: "Sitio web para un servicio de inspección de vehículos usados en Uruguay.",
    revisionModal1: "Revisión Automotriz es un servicio de inspección de vehículos que ayuda a compradores de autos usados a tomar decisiones informadas.",
    revisionModal2: "Desarrollé el sitio web con React y Bootstrap.",
    revisionModal3: "El sitio incluye información sobre el proceso de inspección y los beneficios del servicio.",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("EN");
  const [transitionKey, setTransitionKey] = useState(0);

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === "EN" ? "ES" : "EN"));
    setTransitionKey((prev) => prev + 1);
  }, []);

  const t = useCallback(
    (key) => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, transitionKey }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
